stages:
    - build
    - deploy

image: web:latest

before_script:
    - eval $(ssh-agent -s)
    # to connect staging server and be allowed to clone ACF on GitLab
    - echo "$CI_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$STAGING_HOST_KEY" >> ~/.ssh/known_hosts
    - echo "$GITLAB_HOST_KEY" >> ~/.ssh/known_hosts

#cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    untracked: true
#    paths:
#        - content/mu-plugins/
#        - content/plugins/
#        - content/themes/cardinal/assets/
#        - content/themes/cardinal/node_modules/
#        - vendor/
#        - wp/

build:
    stage: build
    artifacts:
        paths:
        - content/mu-plugins/
        - content/plugins/
        - content/themes/cardinal/assets/
        - content/themes/cardinal/node_modules/
        - vendor/
        - wp/
    script:
        # install build dependencies
        - yarn --cwd content/themes/cardinal/ install --frozen-lockfile
        # build assets
        - yarn --cwd content/themes/cardinal run gulp --prod
        # install prod dependencies
        - composer install --no-dev --optimize-autoloader
        - yarn --cwd content/themes/cardinal install --prod --frozen-lockfile
    only:
        - master

.deploy:
    stage: deploy
    script:
        # instance
        - mv config.production.php config.php
        - mv wp-cli.production.yml wp-cli.yml
        - mv .htaccess.production .htaccess
        - mv .ovhconfig.production .ovhconfig
        # clean before upload
        #- rm -rf .git gulpfile.js content/themes/*/src
        #- find . -iname ".backup-exclude" -delete
        # configure
        - sed -i "s|<DB_NAME>|$DB_NAME|g" config.php
        - sed -i "s|<DB_USER>|$DB_USER|g" config.php
        - sed -i "s|<DB_PASS>|$DB_PASS|g" config.php
        - sed -i "s|<DB_HOST>|$DB_HOST|g" config.php
        - sed -i "s|<URL>|$DEPLOY_URL|g" wp-cli.yml
        # deploy
        #- echo "put -rp . $DEPLOY_PATH" > /tmp/batch_deploy
        #- sftp -b /tmp/batch_deploy $DEPLOY_SERVER
        - echo "Deploy to $DEPLOY_TARGET"
        - rsync -zrpli --chmod=D2775,F664 --delete --exclude-from=.deploy-exclude . $DEPLOY_TARGET

deploy_staging:
    extends: .deploy
    variables:
        DB_NAME: $STAGING_DB_NAME
        DB_USER: $STAGING_DB_USER
        DB_PASS: $STAGING_DB_PASS
        DB_HOST: $STAGING_DB_HOST
        DEPLOY_URL: $STAGING_URL
        DEPLOY_PATH: $STAGING_PATH
        DEPLOY_SERVER: $STAGING_SERVER
        DEPLOY_TARGET: $STAGING_TARGET
    environment:
        name: staging
        url: $DEPLOY_URL
    only:
        - master

deploy_production:
    extends: .deploy
    variables:
        DB_NAME: $PRODUCTION_DB_NAME
        DB_USER: $PRODUCTION_DB_USER
        DB_PASS: $PRODUCTION_DB_PASS
        DB_HOST: $PRODUCTION_DB_HOST
        DEPLOY_URL: $PRODUCTION_URL
        DEPLOY_PATH: $PRODUCTION_PATH
        DEPLOY_SERVER: $PRODUCTION_SERVER
        DEPLOY_TARGET: $PRODUCTION_TARGET
    environment:
        name: production
        url: $DEPLOY_URL
    when: manual
    only:
        - master
