# https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-dev.html
name: linghun-cardinal
services:
    php:
        image: webdevops/php-dev:8.0-alpine
        working_dir: /app
        volumes:
            - .:/app
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            fpm.pool.listen: /app/php-fpm.sock
            fpm.pool.listen.owner: application
            fpm.pool.listen.group: application
