# https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-dev.html
version: '3'
services:
    php:
        user: "${UID}:${GID}"
        image: webdevops/php-dev:7.4-alpine
        volumes:
            - .:/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - fpm.pool.listen=/app/php-fpm.sock
            - fpm.pool.listen.owner=${UID}
            - fpm.pool.listen.group=${GID}
            - WEB_DOCUMENT_ROOT=/app
            - XDEBUG_MODE=debug,profile
            - XDEBUG_START_WITH_REQUEST=trigger
            - XDEBUG_CLIENT_HOST=host.docker.internal
            - PHP_POST_MAX_SIZE=128M
            - PHP_UPLOAD_MAX_FILESIZE=128M
